name: Language API learning

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Language api call 1
        id: language1
        run: |
          echo lang1=$(curl --location 'https://api.github.com/repos/santhosh162000/react-node-cicd/languages' --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN_1 }}' | jq 'to_entries | max_by(.value) | .key') >> $GITHUB_ENV
        shell: bash
      - name: Language api call 2
        id: language2
        run: |
          echo lang2=$(curl --location 'https://api.github.com/repos/santhosh162000/fullphpcrud/languages' --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN_1 }}' | jq 'to_entries | max_by(.value) | .key') >> $GITHUB_ENV
        shell: bash
      - name: Check Languages
        run: |
          OUTPUT1="${{ env.lang1 }}"
          OUTPUT2="${{ env.lang2 }}"

          echo "Branches in santhosh162000/react-node-cicd: $OUTPUT1"
          echo "Branches in santhosh162000/fullphpcrud: $OUTPUT2"
