name: Learning Github API

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.test.outputs.contributor }}
    steps:
      - name: Contributor api call 1
        id: test
        run: |
          url="https://api.github.com/repos/santhosh16200/react-node-cicd/branches"
          response=$(curl -s "$url")

          branch_names=$(echo "$response" | grep -oP '(?<="name": ")[^"]+')

          echo "$branch_names"
