name: Language API

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.language1.outputs.lang }}
      output2: ${{ steps.language2.outputs.lang }}
    steps:
      - name: Language api call 1
        id: language1
        run: |
          echo lang=$(curl --location 'https://api.github.com/repos/santhosh162000/react-node-cicd/languages' --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN_1 }}' | jq 'to_entries | max_by(.value) | .key') >> $GITHUB_ENV
        shell: bash
      - name: Language api call 2
        id: language2
        run: |
          echo lang=$(curl --location 'https://api.github.com/repos/santhosh162000/fullphpcrud/languages' --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN_1 }}' | jq 'to_entries | max_by(.value) | .key') >> $GITHUB_ENV
        shell: bash
      - name: Check Languages
        run: |
          OUTPUT1="${{ steps.language1.outputs.lang }}"
          OUTPUT2="${{ steps.language2.outputs.lang }}"

          echo "Branches in santhosh162000/react-node-cicd: $OUTPUT1"
          echo "Branches in santhosh162000/fullphpcrud: $OUTPUT2"
