name: Approve Pull Request
on: 
  workflow_dispatch

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  
jobs:
  githubactionsbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get Recent PR Number
        id: pr_number
        run: |
          response=$(curl -s --request GET \
            --url "https://api.github.com/repos/${{ github.repository }}/pulls" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json")

          pr_number=$(echo "$response" | jq -r 'first(.[]).number')
          echo "::set-output name=pr_number::$pr_number"

      - name: Use PR Number
        run: |
          pr_number=${{ steps.pr_number.outputs.pr_number }}
          echo "Recent PR number: $pr_number"   
