name: Approve Pull Request
on: 
  workflow_dispatch

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  
jobs:
  githubactionsbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get Pull Request Number
        id: pr
        run: |
          PR_NUMBER=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --url "${{ github.event.pull_request.url }}" \
            --silent | jq -r '.number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
      
      - name: Approve a PR
        run: gh pr review --approve $PR_NUMBER
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: gh pr merge --auto --merge $PR_NUMBER
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
