name: Approve Pull Request
on: 
  workflow_run:
    workflows: [Create Pull Request]
    types: [completed]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Approve a PR
        if: ${{ github.event_name == 'pull_request' }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    
