name: Approve Pull Request
on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Create Pull Request]
    types: [completed]

permissions: write-all
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CI checks
        id: ci
        run: |
          add() {
            echo $(($1 + $2))
          }

          result=$(add 5 3)

          echo "Addition result: $result"

          if [[ $result -ne 8 ]]; then
            echo "::error::Addition result is not equal to 8"
            exit 1
          fi

  githubactionsbot:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PR number checking
        run: echo "${{ github.event.number }}"  

      - name: Get Recent PR Number
        id: pr_number
        run: |
          response=$(curl -s --request GET \
            --url "https://api.github.com/repos/${{ github.repository }}/pulls" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json")

          pr_number=$(echo "$response" | jq -r 'first(.[]).number')
          echo "::set-output name=pr_number::$pr_number"

      - name: Use PR Number
        run: |
          pr_number=${{ steps.pr_number.outputs.pr_number }}
          echo "Recent PR number: $pr_number"  

      - name: Get PR Details
        id: pr_details
        run: |
          pr_number=${{ steps.pr_number.outputs.pr_number }}
          response=$(curl -s --request GET \
            --url "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json")

          pr_author=$(echo "$response" | jq -r '.user.login')
          echo "::set-output name=pr_author::$pr_author"   

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.pr_details.outputs.pr_author != github.actor }}
        run: |
          pr_number=${{ steps.pr_number.outputs.pr_number }}
          gh pr merge --auto --squash "$pr_number"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
