name: First Workflow
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt