name: Set Environment Variables
on:
  workflow_dispatch

jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "VAR1=value1" >> $GITHUB_ENV
          echo "VAR2=value2" >> $GITHUB_ENV

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: env-vars
          path: $GITHUB_ENV
