name: Second Workflow
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Cached Environment Variables
        uses: actions/cache@v2
        with:
          key: env-vars-${{ github.sha }}
          path: $GITHUB_ENV

      - name: Use Environment Variables
        run: |
          echo "VAR1=$VAR1"
          echo "VAR2=$VAR2"
