name: Second Workflow
on:
  workflow_dispatch

jobs:
  consume:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: workflow-output

      - name: Read Output Value
        run: |
          cat workflow-output/output.txt
