name: Use Cached Variables

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore Cached Variables
        uses: actions/cache@v2
        with:
          path: ~/.env
          key: ${{ runner.os }}-env-${{ github.sha }}

      - name: Use Cached Variables
        run: |
          echo "VAR1=$VAR1"
          echo "VAR2=$VAR2"
