name: First Workflow
on:
  fworkflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Output Value
        run: echo "Hello, World!" > output.txt

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow-output
          path: output.txt
