name: Set Environment Variables
on:
  workflow_dispatch

jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "VAR1=value1" >> env-vars.txt
          echo "VAR2=value2" >> env-vars.txt

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: env-vars
          path: env-vars.txt
