name: Use Environment Variables
on:
  workflow_dispatch

jobs:
  use-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: env-vars

      - name: Load environment variables
        run: source ${{ github.workspace }}/$ARTIFACT_PATH

      - name: Print environment variables
        run: |
          echo $VAR1
          echo $VAR2
