name: My Caller Workflow

on: workflow_dispatch
jobs:
  my_job:
      uses: Santhosh-Learning/Actions_Practice_New/.github/workflows/calledworkflow.yml@main
      with:
        my_variable: 'hello world, This is Santhosh'
        num1: 10
        num2: 6

  my_job_1:
      uses: Santhosh-Learning/Actions_Practice_New/.github/workflows/calledworkflow.yml@main
      with:
        my_variable: 'hello world, This is Santhosh'
        num1: 10
        num2: 6      
        FILENAME1: 'Santhosh'
        FILENAME1: 'Murugesan'