name: Workflow check from Workflows_org

on: workflow_dispatch
jobs:
  my_job:
      uses: Santhosh-Learning/Workflows/.github/workflows/test.yml@main
      with:
        my_variable: 'Hello world, This is Santhosh Murugesan'
        num1: 10
        num2: 6

  second_job:
    needs: my_job
    runs-on: ubuntu-latest
    steps:
      - name: Getting output from reusable workflow 1
        run: |
          echo "Output from Job 1 string: ${{ needs.my_job.outputs.firstword }}"    

      - name: Getting output from reusable workflow 2
        run: |
          echo "Output from Job 1 value: ${{ needs.my_job.outputs.firstvalue }}"        
        