name: Workflow check from Workflows_org

on: workflow_dispatch
jobs:
  my_job:
      uses: Santhosh-Learning/Workflows/.github/workflows/test.yml@main
      with:
        num1: 10
        num2: 6

  second_job:
    needs: my_job
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: |
          echo "Output from Job 1: ${{ needs.my_job.outputs.firstword }}"      
        