name: Create Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - dependencies-bot

jobs:
  create_pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        run: |
          gh pr create --title "Merge dependencies-bot to main" --body "This is an automated pull request to merge dependencies-bot branch into main" --base main --head dependencies-bot --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
