name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge dependencies-bot branch to main"
          branch: dependencies-bot
          base: main
          title: "Merge dependencies-bot branch to main"
          body: |
            This is an automated pull request to merge the dependencies-bot branch into main.
