name: default-environment-variables

on: workflow_dispatch

jobs:
  sample-job:
      runs-on: ubuntu-latest
      steps:
        - name: echo-default-env-variables
          run: |
              echo "CI: ${CI}"
              echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
              echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
              echo "GITHUB_ACTION: ${GITHUB_ACTION}"
              echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
              echo "GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}"
              echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
              echo "GITHUB_ACTOR_ID: ${GITHUB_ACTOR_ID}"
              echo "GITHUB_API_URL: ${GITHUB_API_URL}"
              echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
              echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
              echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
              echo "GITHUB_SHA: ${GITHUB_SHA}"
              echo "GITHUB_REF: ${GITHUB_REF}"
              echo "RUNNER_NAME: ${RUNNER_NAME}"
              echo "RUNNER_OS: ${RUNNER_OS}"