name: Dependabot auto-approve
on: 
  - pull_request
  - workflow_dispatch

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  
jobs:
  CI_job:
      uses: Santhosh-Learning/Workflows/.github/workflows/CI-depandabot.yml@main

  dependabot_approve_merge:
      needs: CI_job
      uses: Santhosh-Learning/Workflows/.github/workflows/merge-bot.yml@main    
