name: Dependabot auto-approve
on: 
  - pull_request
  - workflow_dispatch

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  
jobs:
  get-pr-numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR numbers
        id: pr_numbers
        run: |
          response=$(curl -s --request GET \
            --url "https://api.github.com/repos/${{ github.repository }}/pulls" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json")
          pr_numbers=$(echo "$response" | jq -r '.[].number')
          echo "::set-output name=pr_numbers::$pr_numbers"

  CI:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: get-pr-numbers
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CI checks
        id: ci
        run: |
          add() {
            echo $(($1 + $2))
          }

          result=$(add 5 3)

          echo "Addition result: $result"

          if [[ $result -ne 8 ]]; then
            echo "::error::Addition result is not equal to 8"
            exit 1
          fi

  dependabot:
    runs-on: ubuntu-latest
    needs: CI
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        if: ${{ needs.ci.outputs.ci == 'success' }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    
