name: Learning varialbes with outputs

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.output1 == 'hello' }}
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
      - name: Output1 Success
        if: ${{ needs.job1.outputs.output1 == 'hello' }}
        run: echo "Output1 success"
      - name: Output1 Failure
        if: ${{ needs.job1.outputs.output1 != 'hello' }}
        run: echo "Output1 failure"
      - name: Output2 Success
        if: ${{ needs.job1.outputs.output2 == 'world' }}
        run: echo "Output2 success"
      - name: Output2 Failure
        if: ${{ needs.job1.outputs.output2 != 'world' }}
        run: echo "Output2 failure"
