name: Learning varialbes with outputs

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.language.outputs.lang }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - name: api call 
        id: language
        run: |
          echo lang=$(curl --location 'https://api.github.com/repos/santhosh162000/react-node-cicd/languages' --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN_1 }}' | jq 'to_entries | max_by(.value) | .key') >> $GITHUB_OUTPUT
        shell: bash

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.output1 == 'hello' }}
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
          OUTPUT3: ${{needs.job1.outputs.output3}}
        run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT3"
      - name: Output1 Success
        if: ${{ needs.job1.outputs.output1 == 'hello' }}
        run: echo "Output1 success"
      - name: Output1 Failure
        if: ${{ needs.job1.outputs.output1 != 'hello' }}
        run: echo "Output1 failure"
      - name: Output2 Success
        if: ${{ needs.job1.outputs.output2 == 'world' }}
        run: echo "Output2 success"
      - name: Output2 Failure
        if: ${{ needs.job1.outputs.output2 != 'world' }}
        run: echo "Output2 failure"