name: Language API

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.language1.outputs.lang }}
      output2: ${{ steps.language2.outputs.lang }}
    steps:
      - name: Language api call 1
        id: language1
        run: |
          echo lang=$(curl --location 'https://api.github.com/repos/santhosh162000/react-node-cicd/languages' --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN_1 }}' | jq 'to_entries | max_by(.value) | .key') >> $GITHUB_OUTPUT
        shell: bash
      - name: Language api call 2
        id: language2
        run: |
          echo lang=$(curl --location 'https://api.github.com/repos/santhosh162000/react-node-cicd/languages' --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN_1 }}' | jq 'to_entries | max_by(.value) | .key') >> $GITHUB_OUTPUT
        shell: bash

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
      # - name: Output1 Success
      #   if: ${{ needs.job1.outputs.output1 == 'hello' }}
      #   run: echo "Output1 success"
      # - name: Output1 Failure
      #   if: ${{ needs.job1.outputs.output1 != 'hello' }}
      #   run: echo "Output1 failure"
      # - name: Output2 Success
      #   if: ${{ needs.job1.outputs.output2 == 'world' }}
      #   run: echo "Output2 success"
      # - name: Output2 Failure
      #   if: ${{ needs.job1.outputs.output2 != 'world' }}
      #   run: echo "Output2 failure"