name: Create Pull Request from bot branch to main branch
on:
  workflow_dispatch
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge bot branch into main
          base: main
          title: Merge bot branch into main
          body: This pull request merges the changes from the bot branch into the main branch.
