name: Automatic Rebase - Manual branch
on:
  workflow_dispatch
jobs:
  rebasemanual:
    name: Rebase `dependencies` with `main`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: dependencies-manual
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/main
          git push origin dependencies-manual --force