name: API to trigger to second workflow
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Trigger Workflow in Repo2
        env:
          REPO_2_PAT: ${{ secrets.ACTIONS_KEY }}
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $REPO_2_PAT" \
            https://api.github.com/repos/msanthosh-murugesan/ruleset/actions/workflows/workflow_02/dispatches \
            -d '{"ref":"main"}'